Antelope : Permission Operations
pinax-network/substreams-raw-blocks pull request #9
Opened 2024-09-12 19:39 UTC by zolting

Added the Feature Operations table for Antelope

Caveats : 

- I had some trouble handling the optional nature of the new_perm_last_updated and old_perm_last_updated fields. Not sure what would be the best way to handle this. They're commented out of the schema and table insertion logic for now
- The Authority field in a Permission isn't implemented yet, as it's a quite complex type

![Perm ops select](https://github.com/user-attachments/assets/aa416af4-2801-465e-aed4-a636895613e9)

2024-09-12 20:20 UTC, DenisCarriere commented
@zolting if you want to have a look at those conflicts

Other then that, looks good to merge 👍

2024-09-12 20:22 UTC, DenisCarriere requested changes

2024-09-12 20:22 UTC, DenisCarriere commented on blocks/antelope/src/perm_ops.rs
> +    let old_perm = perm_op.old_perm.clone().unwrap_or_default();
For optional fields, you can use `.as_ref().expect("old_perm missing");`

Example: https://github.com/pinax-network/subgraph-antelope-transactions/blob/c6c20a0e4839eb69a2d3090a7d7a339af5345178/src/transactions.rs#L20

2024-09-12 20:34 UTC, DenisCarriere commented
The Authority is definitely useful, however I agree it's a bit more of a complex type

<img width="835" alt="image" src="https://github.com/user-attachments/assets/b8628608-0092-4d1c-9e53-a29b39c6e61b">

Definitely need `Array` support for that one or create more tables to load the `authorities`, it would be useful to have `authority` for all the accounts

## `authorities` TABLE
```sql
    accounts_permissions                 Array(String), // [actor@permission]
    accounts_weights                     Array(UInt32), // [weight]
    keys                                 Array(String), // [PUB_K1_73ci5Qnwfcxs2S7LAMpVRcFr9hc3YcfZ7Nh5pSsCvEFKbQGYhL]
    keys_weight                          Array(UInt32), // [weight]
    threshold                            UInt32
    waits_weight                         Array(UInt32), // [weight]
    waits_wait_sec                       Array(UInt32), // [wait_sec]
```

2024-09-13 01:48 UTC, zolting commented on blocks/antelope/src/perm_ops.rs
> +    let old_perm = perm_op.old_perm.clone().unwrap_or_default();
The sink systematically crashes with expect, as there are many perm_ops with no old_perm

2024-09-13 01:57 UTC, zolting commented
Added the late_updated fields. You can see the different behaviors possible with the old_perm and new_perm fields here:

![old_perm new_perm behaviors](https://github.com/user-attachments/assets/43244ef7-05e5-4ac5-b523-859af4561ab4)

How should we handle the absence of old_perm? Make the clickhouse fields optional? Right now having 0 as value for `old_perm_id` and `old_perm_parent_id` might be a little confusing

2024-09-17 19:35 UTC, DenisCarriere commented
1. Added new tables to handle `authority`:
- accounts
- keys
- waits
2. flattened `perm_ops` to only include latest new permission

> ❗ I do not believe that `new_perm` can be empty, since updating any new permissions would always result in a new permission, I don't believe it can be deleted (but need to confirm that)

## `Authority.*` tables
```sql
CREATE TABLE IF NOT EXISTS accounts
(
    `index`                     UInt32,
    action_index                UInt32,
    actor                       String,
    permission                  LowCardinality(String),
    weight                      UInt32,
);

CREATE TABLE keys
(
    `index`                     UInt32,
    action_index                UInt32,
    public_key                  String,
    weight                      UInt32,
);

CREATE TABLE waits
(
    `index`                     UInt32,
    action_index                UInt32,
    wait_sec                    UInt32,
    weight                      UInt32,
)
```

## Updated Perm Ops

```sql

CREATE TABLE perm_ops
(
    operation                   LowCardinality(String),
    operation_code              UInt8,
    action_index                UInt32,
    id                          UInt64,
    parent_id                   UInt64,
    owner                       String,
    name                        String,
    threshold                   UInt32,
);
```

2024-09-17 19:36 UTC, DenisCarriere approved these changes

2024-09-17 19:37 UTC, DenisCarriere commented on blocks/antelope/src/perm_ops.rs
> +    let old_perm = perm_op.old_perm.clone().unwrap_or_default();
I removed `old_perm` from the schema structure, we only need to handle new permissions

Old permissions can be looked up by past actions

2024-09-17 19:37 UTC, merged